# Generated by Django 5.1.5 on 2025-01-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_article_is_featured_article_is_recent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_recent',
        ),
    ]
