# Generated by Django 5.1.5 on 2025-01-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"permissions": [("add_score", "Can add score to articles")]},
        ),
    ]
