# Generated by Django 5.1.5 on 2025-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_alter_article_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("normal_user", "Normal User"), ("judge", "Judge")],
                max_length=20,
            ),
        ),
    ]
