# Generated by Django 5.1.5 on 2025-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='branch',
            field=models.CharField(choices=[('data_science', 'Data Science'), ('artificial_intelligence', 'Artificial Intelligence'), ('web_development', 'Web Development'), ('cybersecurity', 'Cybersecurity'), ('machine_learning', 'Machine Learning')], default='data_science', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('data_science', 'Data Science'), ('artificial_intelligence', 'Artificial Intelligence'), ('web_development', 'Web Development'), ('cybersecurity', 'Cybersecurity'), ('machine_learning', 'Machine Learning')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('data_science', 'Data Science'), ('artificial_intelligence', 'Artificial Intelligence'), ('web_development', 'Web Development'), ('cybersecurity', 'Cybersecurity'), ('machine_learning', 'Machine Learning')], default='data_science', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
