# Generated by Django 5.1.5 on 2025-02-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_alter_userprofile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('data_science', 'Data Science'), ('artificial_intelligence', 'Artificial Intelligence'), ('web_development', 'Web Development'), ('cybersecurity', 'Cybersecurity'), ('machine_learning', 'Machine Learning')], default='', max_length=50, null=True),
        ),
    ]
